name: Build & Release Flatpak

on:
  push:
    tags:
      - '*'

jobs:
  build-flatpak:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Flatpak info
        run: flatpak --version

      - name: Add Flathub remote
        run: |
          flatpak remote-add --user --if-not-exists \
          flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak update -y --appstream flathub        

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Flatpak bundle
        run: ./gradlew packageFlatpakReleaseDistributable


      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: app/build/flatpak/*.flatpak

      - name: Upload tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: tar-gz-bundle
          path: app/build/distributions/de.stefan_oltmann.mines-*.tar.gz

  release:
    needs: build-flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Flatpak artifact
        uses: actions/download-artifact@v4
        with:
          name: flatpak-bundle

      - name: Download tar.gz artifact
        uses: actions/download-artifact@v4
        with:
          name: tar-gz-bundle

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.flatpak
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
